-- 1) holdings
create table public.holdings (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references auth.users(id) on delete cascade,
  category    text not null check (category in ('kr','us','crypto')),
  symbol      text not null,
  name        text not null,
  created_at  timestamptz not null default now(),
  unique (user_id, symbol)
);
create index holdings_user_id_idx on public.holdings (user_id);

-- 2) transactions
create table public.transactions (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references auth.users(id) on delete cascade,
  holding_id  bigint not null references public.holdings(id) on delete cascade,
  type        text not null check (type in ('buy','sell')),
  quantity    numeric not null check (quantity > 0),
  price       numeric not null check (price >= 0),
  date        date not null,
  fee         numeric not null default 0 check (fee >= 0),
  created_at  timestamptz not null default now()
);
create index transactions_user_id_idx  on public.transactions (user_id);
create index transactions_holding_idx on public.transactions (holding_id);

-- 3) user_settings (1:1)
create table public.user_settings (
  user_id     uuid primary key references auth.users(id) on delete cascade,
  target      jsonb not null default '{"kr":30,"us":50,"crypto":20}',
  fx_rate     numeric not null default 1380 check (fx_rate > 0),
  updated_at  timestamptz not null default now()
);

-- 4) ai_usage (서버가 service_role로만 갱신)
create table public.ai_usage (
  user_id     uuid not null references auth.users(id) on delete cascade,
  usage_date  date not null,
  count       integer not null default 0,
  primary key (user_id, usage_date)
);

-- 5) allowed_emails (초대제)
create table public.allowed_emails (
  email       text primary key,
  invited_by  uuid references auth.users(id),
  created_at  timestamptz default now()
);
